<template>
    <section>
        <h1 class="mt-5">Halaman Home</h1>
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h4>Ini adalah card 1</h4>
                        <p>
                            Lorem ipsum, dolor sit amet consectetur adipisicing
                            elit. Sint repudiandae dolores possimus minus
                            numquam rem, quidem qui suscipit illo nemo
                            consectetur, facilis, commodi nihil atque nostrum.
                            Illum ea ducimus excepturi possimus. Illo, officiis
                            officia suscipit numquam voluptatum perferendis sed
                            cumque dolores incidunt similique quo quam earum
                            ipsam quae, nemo
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h4>Ini adalah card 2</h4>
                        <p>
                            Lorem ipsum, dolor sit amet consectetur adipisicing
                            elit. Sint repudiandae dolores possimus minus
                            numquam rem, quidem qui suscipit illo nemo
                            consectetur, facilis, commodi nihil atque nostrum.
                            Illum ea ducimus excepturi possimus. Illo, officiis
                            officia suscipit numquam voluptatum perferendis sed
                            cumque dolores incidunt similique quo quam earum
                            ipsam quae, nemo voluptatem a obcaecati odio tempore
                            fugiat ab sint veritatis?
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h4>Ini adalah card 3</h4>
                        <p>
                            Lorem ipsum, dolor sit amet consectetur adipisicing
                            elit. Sint repudiandae dolores possimus minus
                            numquam rem, quidem qui suscipit illo nemo
                            consectetur, facilis, commodi nihil atque nostrum.
                            Illum ea ducimus excepturi possimus. Illo, officiis
                            officia suscipit numquam voluptatum perferendis sed
                            cumque dolores incidunt similique quo quam earum
                            ipsam quae, nemo voluptatem a obcaecati odio tempore
                            fugiat ab sint veritatis? Illum
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
</template>

<script></script>

<style></style>
